### PR TITLE
Fixed a bug in Files/processFile and added SiteLogoUrl to IWebSettings

### PR DESCRIPTION
**Pull request by olemp**

### CODE REVIEW

**Comment by olemp** [comment]
@patrick-rodgers After merging this, could you up the version a tidy bit, and publish to NPM? We're trying to move away from our fork for one of our projects, and fetch the module directly from NPM instead.

**Comment by patrick-rodgers** [comment]
Sure I can - will take me a bit to get that setup and not sure I will be done today - but will this week. You want it to be version 1? Is it ready for that? I can publish a beta as well if that is better.

**Comment by olemp** [comment]
A beta will do for now. It's not 1.0.0 yet, more like 0.9.0 or 0.9.0beta or something.

**Comment by olemp** [comment]
Thanks for a swift response btw.

**Comment by patrick-rodgers** [comment]
Ok, I added the publish tasks and did a publish of a beta: sp-pnp-provisioning@0.0.2-beta.0

Give it a shot, I also added a few issues here if you want to look at them, up to you.

**Comment by olemp** [comment]
I will have a look. Thanks!

**Pull request merged**
